### ISSUE TITLE
Prevent GRS stream the error to css file

### ISSUE THREAD

**Issue by arnoldsimha** [sindresorhus/gulp-ruby-sass#239]
Hi,
I have newbie question (tried to find solution with no success). Is it possible to keep previous good css compiled file if I have sass error? I only want display the error in command view

**Comment by robwierzbowski** [comment]
As far as I know that isn't possible with Sass. In order to keep this
module as simple as it can be it's only a wrapper for Sass, and doesn't add
any extra functionality.

If you find a way with Sass to print the error to the console and not
replace the erroring file, you should be able to do the same thing with
GRS. Any option you set in GRS will be passed directly to the Sass
executable.

On Saturday, July 25, 2015, arnoldsimha <notifications@github.com> wrote:

> Hi,
> I have newbie question (tried to find solution with no success). Is it
> possible to keep previous good css compiled file if I have sass error? I
> only want display the error in command view
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/239>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by arnoldsimha** [comment]
Thank you.
